//HEADER
#include <lpcIsp.h>

//SLICE
const char* lpcIspErrorMessage(int code) {
	switch(code) {
		case LPC_ISP_CMD_SUCCESS:			return "CMD_SUCCESS";
		case LPC_ISP_INVALID_COMMAND:			return "INVALID_COMMAND";
		case LPC_ISP_SRC_ADDR_ERROR:			return "SRC_ADDR_ERROR";
		case LPC_ISP_DST_ADDR_ERROR:			return "DST_ADDR_ERROR";
		case LPC_ISP_SRC_ADDR_NOT_MAPPED:		return "SRC_ADDR_NOT_MAPPED";
		case LPC_ISP_DST_ADDR_NOT_MAPPED:		return "DST_ADDR_NOT_MAPPED";
		case LPC_ISP_COUNT_ERROR:			return "COUNT_ERROR";
		case LPC_ISP_INVALID_SECTOR:			return "INVALID_SECTOR";
		case LPC_ISP_SECTOR_NOT_BLANK:			return "SECTOR_NOT_BLANK";
		case LPC_ISP_SECTOR_NOT_PREPARED:		return "SECTOR_NOT_PREPARED";
		case LPC_ISP_COMPARE_ERROR:			return "COMPARE_ERROR";
		case LPC_ISP_BUSY:				return "BUSY";
		case LPC_ISP_PARAM_ERROR:			return "PARAM_ERROR";
		case LPC_ISP_ADDR_ERROR:			return "ADDR_ERROR";
		case LPC_ISP_ADDR_NOT_MAPPED:			return "ADDR_NOT_MAPPED";
		case LPC_ISP_CMD_LOCKED:			return "CMD_LOCKED";
		case LPC_ISP_INVALID_CODE:			return "INVALID_CODE";
		case LPC_ISP_INVALID_BAUD_RATE:			return "INVALID_BAUD_RATE";
		case LPC_ISP_INVALID_STOP_BIT:			return "INVALID_STOP_BIT";
		case LPC_ISP_CODE_READ_PROTECTION:		return "CODE_READ_PROTECTION";
		case LPC_ISP_INVALID_FLASH_UNIT:		return "INVALID_FLASH_UNIT";
		case LPC_ISP_USER_CODE_CHECKSUM:		return "USER_CODE_CHECKSUM";
		case LPC_ISP_ERROR_SETTING_ACTIVE_PARTITION:	return "ERROR_SETTING_ACTIVE_PARTITION";
		default:					return "UNDEFINED ERROR";
	}
}


//SLICE

