#ifndef __unionized_h
#define __unionized_h

/** @file
 * @brief this file should be included in all files using unions generated by unionize.pl .
 *
 * unionize.pl heavily eases the definition of typical register files used in microcontroller peripherals.
 */

#define PACKED4 __attribute__((packed,aligned(4)))
#define PACKED2 __attribute__((packed,aligned(2)))
#define PACKED __attribute__((packed))

// this is simply a text pattern without further functionality. It's used by unionize.pl to mark automatically 
// generated lines.
#define unionized

#endif

